import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Layout from '@components/layout'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          {/* <link
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Open+Sans:wght@400;600&display=swap"
            rel="stylesheet"
          /> */}
      <body className={inter.className}>
<Layout>

        {children}
</Layout>
        </body>
    </html>
  );
}
